name: CI 

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - name: Build and Test  
        run: |
          # Add your test commands here
          if [ -f "index.html"]; then 
            echo "index.html exists. Build and test successful!"
          else 
            echo "Error: index.html not found. Build and test failed."
            exit 1
          fi 
